CREATE OR REPLACE PROCEDURE SET_TIMESTAMP_DONE AUTHID CURRENT_USER
    IS
    BEGIN
        FOR I IN (SELECT ID AS V_STATISTIC_ID FROM T_STATISTIC)
        LOOP
   		UPDATE T_STATISTIC SET TIMESTAMP_PRACTICE_DONE = CURRENT_TIMESTAMP WHERE ID = I.V_STATISTIC_ID
           AND NOT EXISTS (SELECT COUNT(*) FROM T_VOCABULARY_IN_STATISTIC WHERE STATISTIC_ID = I.V_STATISTIC_ID GROUP BY CORRECT HAVING CORRECT IS NULL);
        COMMIT;
        END LOOP;
    END;
/
