FUNCTION GET_VOCABULARY_BY_ID(P_VOCABULARY_ID IN NUMBER)
RETURN VARCHAR2;
FUNCTION GET_RESSOURCE(P_RESSOURCE_ID IN NUMBER)
RETURN VARCHAR2;
FUNCTION GET_TRANSLATION_BY_VOCABULARY_ID (P_VOCABULARY_ID IN NUMBER)
RETURN VARCHAR2;
