CREATE TABLE T_STATISTIC(
ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
TIMESTAMP_GERNERATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
TIMESTAMP_PRACTICE_DONE TIMESTAMP(6),
USER_ID NUMBER NOT NULL,
CONSTRAINT STATISTIC_PK PRIMARY KEY(ID),
CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES T_USER(ID)
);
