CREATE TABLE T_USER(
ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
EMAIL VARCHAR2(128) NOT NULL,
FIRSTNAME VARCHAR(32) NOT NULL,
LASTNAME VARCHAR(32) NOT NULL,
CONSTRAINT USER_PK PRIMARY KEY(ID)
);
