CREATE TABLE T_VOCABULARY_IN_USER(
ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
CATEGORY NUMBER NOT NULL,
COUNTER NUMBER NOT NULL,
USER_ID NUMBER NOT NULL,
VOCABULARY_ID NUMBER NOT NULL,
TIMESTAMP_LAST_PRACTICE TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT VOCABULARY_IN_USER_PK PRIMARY KEY (VOCABULARY_ID, USER_ID),
CONSTRAINT USER_VOC_FK FOREIGN KEY (USER_ID) REFERENCES T_USER(ID),
CONSTRAINT VOCABULARY_USER_FK FOREIGN KEY (VOCABULARY_ID) REFERENCES T_VOCABULARY(ID)
);
