BEGIN


INSERT_NEW_LANGUAGE('EN');
INSERT_NEW_LANGUAGE('DE');

INSERT_NEW_UNIT('LEKTION 1');

INSERT_NEW_USER('Lisa', 'Milde', 'lisa.milde@triology.de');

INSERT_NEW_VOCABULARY('option', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('analytical', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to apply', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('workflow', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('training', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to perform', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('outside infiltration', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to advise', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('carrer', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('job title', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to evaluate', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('broad', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('database', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('implementation', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to recommend', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to design', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('performance', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('findings', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to troubleshoot', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to operate', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('devices', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('overall', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('graphic', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('functionality', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to assist', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to integrate', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('website', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('apprenticeship', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('benefit', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('efficiency', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('local area network (LAN)', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('several', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('verbal', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to schedule', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('advice', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('focus', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to secure', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('storage', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('system analyst', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to handle', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('to outline', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('encryption', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('confidental', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('suggestion', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('maintenance', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('wide area network (WAN)', 'LEKTION 1', 'EN');
INSERT_NEW_VOCABULARY('impact', 'LEKTION 1', 'EN');

INSERT_NEW_VOCABULARY('Alternative, Möglichkeit', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('analytisch', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('anwenden', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Arbeitsablauf', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Ausbildung, Lehre', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('ausfuehren, verrichten', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Außeninfiltration', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('beraten', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Beruf, Laufbahn, Karriere', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Berufsbezeichnung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('bewerten, auswerten, beurteilen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('breit angelegt', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Datenbank', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Einfuehrung, Umsetzung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('empfehlen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('entwerfen, konstruieren', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Ergebnis, Erfolg', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Ergebnisse', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Fehler beheben', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('funktionieren, anwenden, arbeiten', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Geraete', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('gesamt', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('grafisch', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Handhabbarkeit', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('helfen, beistehen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('integrieren', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Internetseite', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Lehre, Ausbildung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Leistung, Nutzen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Leistungsfähigkeit, Effizienz', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('lokales Netzwerk', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('mehrere', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('muendlich', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('planen, ansetzen, anberaumen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Rat, Beratung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Schwerpunkt', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('sichern, absichern, schuetzen', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Speicherung, Lagerung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Systemberater', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('umgehen mit', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('umreissen, skizzieren', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Verschluesselung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('vertraulich', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Vorschlag', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Wartung', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Weitverkehrsnetzwerk', 'LEKTION 1', 'DE');
INSERT_NEW_VOCABULARY('Wirkung, Einfluss', 'LEKTION 1', 'DE');

INSERT_NEW_TRANSLATION('Alternative', 'option', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Möglichkeit', 'option', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('analytisch', 'analytical', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('anwenden', 'to apply', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Arbeitsablauf', 'workflow', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Ausbildung', 'training', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Lehre', 'training', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('ausfuehren', 'to perform', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('verrichten', 'to perform', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Außeninfiltration', 'outside infiltration', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('beraten', 'to advise', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Beruf', 'carrer', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Laufbahn', 'carrer', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Karriere', 'carrer', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Berufsbezeichnung', 'job title', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('bewerten', 'to evaluate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('auswerten', 'to evaluate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('beurteilen', 'to evaluate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('breit angelegt', 'broad', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Datenbank', 'database', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Einfuehrung', 'implementation', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Umsetzung', 'implementation', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('empfehlen', 'to recommend', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('entwerfen', 'to design', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('konstruieren', 'to design', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Ergebnis', 'performance', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Erfolg', 'performance', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Ergebnisse', 'findings', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Fehler beheben', 'to troubleshoot', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('funktionieren', 'to operate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('anwenden', 'to operate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('arbeiten', 'to operate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Geraete', 'devices', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('gesamt', 'overall', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('grafisch', 'graphic', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Handhabbarkeit', 'functionality', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('helfen', 'to assist', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('beistehen', 'to assist', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('integrieren', 'to integrate', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Internetseite', 'website', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Lehre', 'apprenticeship', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Ausbildung', 'apprenticeship', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Leistung', 'benefit', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Nutzen', 'benefit', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Leistungsfähigkeit', 'efficiency', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Effizienz', 'efficiency', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('lokales Netzwerk', 'local area network (LAN)', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('mehrere', 'several', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('muendlich', 'verbal', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('planen', 'to schedule', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('ansetzen', 'to schedule', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('anberaumen', 'to schedule', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Rat', 'advice', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Beratung', 'advice', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Schwerpunkt', 'focus', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('sichern', 'to secure', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('absichern', 'to secure', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('schuetzen', 'to secure', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Speicherung', 'storage', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Lagerung', 'storage', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Systemberater', 'system analyst', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('umgehen mit', 'to handle', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('umreissen', 'to outline', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('skizzieren', 'to outline', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Verschluesselung', 'encryption', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('vertraulich', 'confidental', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Vorschlag', 'suggestion', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Wartung', 'maintenance', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Weitverkehrsnetzwerk', 'wide area network (WAN)', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Wirkung', 'impact', 'LEKTION 1', 'DE');
INSERT_NEW_TRANSLATION('Einfluss', 'impact', 'LEKTION 1', 'DE');

INSERT_NEW_TRANSLATION('option', 'Alternative, Möglichkeit', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('analytical', 'analytisch', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to apply', 'anwenden', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('workflow', 'Arbeitsablauf', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('training', 'Ausbildung, Lehre', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to perform', 'ausfuehren, verrichten', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('outside infiltration', 'Außeninfiltration', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to advise', 'beraten', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('carrer', 'Beruf, Laufbahn, Karriere', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('job title', 'Berufsbezeichnung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to evaluate', 'bewerten, auswerten, beurteilen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('broad', 'breit angelegt', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('database', 'Datenbank', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('implementation', 'Einfuehrung, Umsetzung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to recommend', 'empfehlen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to design', 'entwerfen, konstruieren', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('performance', 'Ergebnis, Erfolg', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('findings', 'Ergebnisse', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to troubleshoot', 'Fehler beheben', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to operate', 'funktionieren, anwenden, arbeiten', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('devices', 'Geraete', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('overall', 'gesamt', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('graphic', 'grafisch', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('functionality', 'Handhabbarkeit', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to assist', 'helfen, beistehen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to integrate', 'integrieren', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('website', 'Internetseite', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('apprenticeship', 'Lehre, Ausbildung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('benefit', 'Leistung, Nutzen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('efficiency', 'Leistungsfähigkeit, Effizienz', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('local area network (LAN)', 'lokales Netzwerk', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('several', 'mehrere', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('verbal', 'muendlich', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to schedule', 'planen, ansetzen, anberaumen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('advice', 'Rat, Beratung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('focus', 'Schwerpunkt', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to secure', 'sichern, absichern, schuetzen', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('storage', 'Speicherung, Lagerung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('system analyst', 'Systemberater', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to handle', 'umgehen mit', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('to outline', 'umreissen, skizzieren', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('encryption', 'Verschluesselung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('confidental', 'vertraulich', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('suggestion', 'Vorschlag', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('maintenance', 'Wartung', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('wide area network (WAN)', 'Weitverkehrsnetzwerk', 'LEKTION 1', 'EN');
INSERT_NEW_TRANSLATION('impact', 'Wirkung, Einfluss', 'LEKTION 1', 'EN');

END;
