FUNCTION GET_VOCABULARY_BY_ID(P_VOCABULARY_ID IN NUMBER)
    RETURN VARCHAR2
    IS V_VOCABULARY VARCHAR2(256);
    BEGIN
        SELECT VOCABULARY INTO V_VOCABULARY FROM T_VOCABULARY WHERE ID = P_VOCABULARY_ID;
        RETURN V_VOCABULARY;
    END GET_VOCABULARY_BY_ID;

FUNCTION GET_RESSOURCE(P_RESSOURCE_ID IN NUMBER)
    RETURN VARCHAR2
    IS V_RESSOURCE VARCHAR2(256);
    BEGIN
        SELECT RESSOURCE INTO V_RESSOURCE FROM T_RESSOURCES WHERE ID = P_RESSOURCE_ID;
        RETURN V_RESSOURCE;
    END GET_RESSOURCE;

FUNCTION GET_TRANSLATION_BY_VOCABULARY_ID (P_VOCABULARY_ID IN NUMBER)
    RETURN VARCHAR2
    IS V_TRANSLATION VARCHAR2(256);
    BEGIN
        SELECT TRANSLATION INTO V_TRANSLATION FROM T_TRANSLATION WHERE VOCABULARY_ID = P_VOCABULARY_ID;
        RETURN V_TRANSLATION;
    END GET_TRANSLATION_BY_VOCABULARY_ID;
