CREATE VIEW V_ALL_VOCABULARY_ENTRIES AS
SELECT A.*, COALESCE(VU.CATEGORY, 0) AS CATEGORY FROM
(SELECT US.ID AS USER_ID, U.ID AS UNIT_ID, U.NAME AS UNIT_NAME, V.ID AS VOC_ID, V.VOCABULARY, V.LANGUAGE_ID AS VOC_LANG_ID, VL.NAME AS VOC_LANG, T.ID AS TRA_ID, T.TRANSLATION, T.LANGUAGE_ID AS TRA_LANG_ID, LL.NAME AS TRA_LANG
FROM T_USER US, T_VOCABULARY V
INNER JOIN T_TRANSLATION T ON V.ID = T.VOCABULARY_ID
INNER JOIN T_UNIT U ON V.UNIT_ID = U.ID
INNER JOIN T_LANGUAGE VL ON VL.ID = V.LANGUAGE_ID
INNER JOIN T_LANGUAGE LL ON LL.ID = T.LANGUAGE_ID) A
LEFT JOIN T_VOCABULARY_IN_USER VU ON VU.USER_ID = A.USER_ID;
